log:
  level: debug
  disable_sentry: true

db:
  url: postgres://usdt:usdt@localhost:usdt/postgres?sslmode=disable

listener:
  addr: localhost:8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: usdt_listening
  service_port: 80

api_key: 02b3e560f25f4d0db54c9fa4519c7c24
