log:
  level: debug
  disable_sentry: true

db:
  url: postgres://postgres:usdt@localhost:5440/postgres?sslmode=disable

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: usdt_listening
  service_port: 80
